set(COROAMALIB_UNIT_TESTS_ROOT ${CMAKE_SOURCE_DIR}/lib)

include_directories(${COROAMALIB_UNIT_TESTS_ROOT}/../../include/)

set(COROAMALIB_UNIT_TESTS_SOURCE_FILES
    ${COROAMALIB_UNIT_TESTS_ROOT}/Types.cpp)